import "bootstrap";
import "./style.css";
import "./assets/img/rigo-baby.jpg";
import "./assets/img/4geeks.ico";
window.onload = function () {
  let excuse = document.getElementById("exuse");
  excuse.innerHTML = "";
  let encabezado = document.getElementById("encabezado");
  encabezado.innerHTML = "Oh no the page doesn't load because...";
  let who = ['The dog', 'My grandma', 'The mailman', 'My bird'];
  let action = ['ate', 'peed', 'crushed', 'broke'];
  let what = ['my homework', 'my phone', 'the car'];
  let when = ['before the class', 'when I was sleeping', 'while I was exercising', 'during my lunch', 'while I was praying'];
  let randomWho = Math.floor(Math.random() * who.length);
  console.log(randomWho);
  let randomAction = Math.floor(Math.random() * action.length);
  console.log(randomAction);
  let randomWhat = Math.floor(Math.random() * what.length);
  console.log(randomWhat);
  let randomWhen = Math.floor(Math.random() * when.length);
  console.log(randomWhen);
  excuse.innerHTML = who[randomWho] + " " + action[randomAction] + " " + what[randomWhat] + " " + when[randomWhen];
};